travis:
  secure:
    BINSTAR_TOKEN: RaMeL5X8aztvPXGGQCQeQr/x1JQnHJLmJiIbPqwCpHvKBgn3WMJoU2eF7gfOaIrnn63qKK3ewrhKQZjeP5HN/YIW9YJH9buWCY2a1gvTJscbSL9zw2SWxTnUB8Xz7ZTWi4INzKqtwR3A2d7uMSi+hv8iSbaBH/Tyi8pG+KgVyaPh+4XLszj/qUDcJFYQ2BCaRPceInEei+4igALhjb9JDhcrLgwoyg94U9f5ErMfrUiPdqVWtqFcIcx/gpX29yoK+e2zo5/TpGe8yJ+WUNAXLigKzkNz2E00U94I0fhY7w5xPusd/6fDz6dRmvspwtU12GooOEx2r709a5PVwmGn4oTCNB9IYyEKLCiAy0/xBnusFOEiChCCJL/7KA4l4BYka7S+C95pp+GmWd9j1ztnxudgOyUCej5d8kZQdytmaLYKtwnOGefBY0NPhYoxQixcRoSIEAyPHkUjxQ7o4X4DtP25rppZ3LzosWe3SdexP530gpv3dSAdpQiyCje84BilkrPEh4gMBxKvVdMTgRovlHjZjleUpmOmE82UDEsTdxciTpXCuuidj5qUAYs/WhNc179QVO3Is1EeBroYe0jmsF94CYB6yIjEbimVz6KddeTyTMAnYwJDwHU7Ac/slvnz9OTlLRdGmn9tjfHIRHHDEMNyKaq+XhM2FZThDblkI+0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
